- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Update cache if it's older than 1 hour
        
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Create project directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Generate and copy .env file
      template:
        src: .env.j2
        dest: "{{ project_path }}/.env"
        mode: '0600'

    - name: Pull Redmine Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull
    
    - name: Run Redmine container
      docker_container:
        name: redmine-docker
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        env_file: "{{ project_path }}/.env"
        ports:
          - "{{ host_port }}:{{ container_port }}"