- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
  roles:
    - geerlingguy.docker
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker


  tasks:
    - name: Create project directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Generate and copy .env file
      template:
        src: .env.j2
        dest: "{{ project_path }}/.env"
        mode: '0600'

    - name: Check if .env file exists
      stat:
        path: "{{ project_path }}/.env"
      register: env_file

    - name: Check .env file status
      debug:
        msg: ".env file created successfully"
      when: env_file.stat.exists

    - name: Pull Redmine Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull
    
    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine-docker
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        env_file: "{{ project_path }}/.env"
        volumes:
          - "{{ project_path }}/files:/usr/src/redmine/files"
        ports:
          - "{{ host_port }}:{{ container_port }}"
    
- hosts: webservers
  become: yes

  roles:
    - role: datadog.dd.agent
      vars:
        datadog_site: "datadoghq.eu"
        datadog_checks:
          http_check:
            init_config:
            instances:
              - name: "Redmine healthcheck"
                url: "http://localhost:{{ host_port }}"
                timeout: 3
                method: GET